[versions]
spring-boot = "2.7.5"
lombok = "1.18.24"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot"}
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot"}
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot"}
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot"}
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }